import { Outlet, NavLink, Link } from "react-router-dom";

import logo from "../../assets/logo.svg";

import styles from "./Layout.module.css";

import { useLogin } from "../../authConfig";

import { LoginButton } from "../../components/LoginButton";

const Layout = () => {
    return (
        <div className={styles.layout}>
            <header className={styles.header} role={"banner"}>
                <div className={styles.headerContainer}>
                    <Link to="/" className={styles.headerTitleContainer}>
                        <img src={logo} alt="Novartis logo" aria-label="Link to home page" className={styles.headerLogo} />
                        <h3 className={styles.headerTitle}>AI Analytics</h3>
                    </Link>
                    {useLogin && <LoginButton />}
                </div>
            </header>

            <Outlet />
            <footer className={styles.footer}>
                The following content has been automatically generated by an AI. While we strive for accuracy and quality, please note that the information
                provided may not be entirely error-free or up-to-date. We recommend conducting further research to validate and supplement the information
                provided.
            </footer>
        </div>
    );
};

export default Layout;
